var matchups = [
    new MatchUp("Jinx","Vi","rare"),
    new MatchUp("Monke","Humante","rare"),
    new MatchUp("Salt","Sugar","common"),
    new MatchUp("Cat","Dog","common"),
    new MatchUp("Trump","Biden","uncommon"),
    new MatchUp("Putic","Pusic","rare"),
    new MatchUp("God","Devil","common"),
    new MatchUp("Mom","Dad","common"),
    new MatchUp("Brother","Sister","common"),
    new MatchUp("Sun","Moon","common"),
    new MatchUp("Trash","Idiot","uncommon"),
    new MatchUp("Burger","Pljeska","rare"),
    new MatchUp("Burek sa sirom","Burek sa mesom","uncommon"),
    new MatchUp("Burek sa sirom","Sirnica","uncommon"),
    new MatchUp("Steam","Epic Games","uncommon"),
    new MatchUp("CSGO","Valorant","uncommon"),
    new MatchUp("Vandal","Phantom","rare"),
    new MatchUp("Odin","Operator","rare"),
    new MatchUp("Reina","Jett","rare"),
    new MatchUp("Yone","Yasuo","rare"),
    new MatchUp("TFT","ARAM","rare"),
    new MatchUp("forty nity","babagee","rare"),
] 

